authorname: "Myo Minn Oo"
draft: false


title-meta: "McKinnon Lab"
description-meta: "Mucosal Immunology Lab"


project:
  type: website
  output-dir: docs  
  preview:
    port: 4200


website:
  title: "McKinnon Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: [lux, styles.scss]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
      
editor: visual


execute: 
  freeze: auto